# Generated by Django 4.1.2 on 2022-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_post_comment_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_comment",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="post_like",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="user_post",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
